AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
